ci: build: add docs in ci/developer builds
To make it a little bit more obvious that those should be updated as
well...

On Alpine it fails (as below), so we've disabled it for now.

When gtkdoc-mkhtml calls xsltproc, the latter throws dozens of errors and
fails to produce the libkmod.devhelp2 file. Which meson tries to move
and fails.

  Error: no ID for constraint linkend: "int"

Signed-off-by: Emil Velikov <emil.l.velikov@gmail.com>
Link: https://github.com/kmod-project/kmod/pull/94
Signed-off-by: Lucas De Marchi <lucas.de.marchi@gmail.com>