ci: Fix alpine setup
linux-edge-dev is failing in alpine:

	ERROR: unable to select packages:
	  linux-edge-dev (no such package):
	    required by: world[linux-edge-dev]
	Error: Process completed with exit code 1.

Use linux-stable instead.

Signed-off-by: Lucas De Marchi <demarchi@kernel.org>